version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger2
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5775:5775/udp"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
    restart: always

  notes-db:
    image: postgres
    container_name: notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - "5432:5432"

  users-db:
    image: postgres
    container_name: users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  keycloack:
    image: jboss/keycloak
    container_name: keycloack
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: users-db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "7070:8080"
    restart: always
